### ISSUE TITLE
⿳、⿲巢狀run-time error

### ISSUE THREAD

**Issue by Chandrayacsa** [sih4sing5hong5/han3_ji7_tsoo1_kian3#18]
輸入「⿺辶⿳宀珤⿲隹貝招」時出現執行錯誤。雖然可用「⿺辶⿳宀珤『⿰隹⿰貝招』」替代，但仍希望回報此問題。Call stack紀錄如下：

java.lang.RuntimeException: 排版工具不支援三個元素的組合方式
	cc.layouttools.MergePieceAdjuster.adjustTzu(MergePieceAdjuster.java:195)
	cc.movabletype.ChineseCharacterMovableTypeTzu.adjust(ChineseCharacterMovableTypeTzu.java:69)
	cc.layouttools.MergePieceAdjuster.遞迴調整(MergePieceAdjuster.java:210)
	cc.layouttools.MergePieceAdjuster.adjustTzu(MergePieceAdjuster.java:154)
	cc.movabletype.ChineseCharacterMovableTypeTzu.adjust(ChineseCharacterMovableTypeTzu.java:69)
	cc.layouttools.MergePieceAdjuster.遞迴調整(MergePieceAdjuster.java:210)
	cc.layouttools.MergePieceAdjuster.adjustTzu(MergePieceAdjuster.java:154)
	cc.movabletype.ChineseCharacterMovableTypeTzu.adjust(ChineseCharacterMovableTypeTzu.java:69)
	cc.layouttools.MergePieceAdjuster.遞迴調整(MergePieceAdjuster.java:210)
	cc.layouttools.MergePieceAdjuster.adjustTzu(MergePieceAdjuster.java:178)
	cc.movabletype.ChineseCharacterMovableTypeTzu.adjust(ChineseCharacterMovableTypeTzu.java:69)
	idsgen.services.IDSgenService.組字(IDSgenService.java:215)
	idsgen.services.IDSgenService.字組成png(IDSgenService.java:275)
	idsgen.services.IDSgenServlet.doGet(IDSgenServlet.java:207)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

連結網址：https://tools.wmflabs.org/idsgen/%E2%BF%BA%E8%BE%B6%E2%BF%B3%E5%AE%80%E7%8F%A4%E2%BF%B2%E9%9A%B9%E8%B2%9D%E6%8B%9B.png?%E5%AD%97%E9%AB%94=%E6%A5%B7%E9%AB%94

**Comment by sih4sing5hong5** [comment]
維基的版本merge進來
就可以修這個bug了

**Comment by sih4sing5hong5** [comment]
謝謝你回報！！

**Comment by MGdesigner** [comment]
好，我來研究怎如何merge回來

**Comment by MGdesigner** [comment]
我merge push回來了，抱歉第一次做不知道這樣好不好。 XD
就再請sih4sing5hong5 check一下。

ps. Jetty的部份，程式我沒改，理論上雖然路徑變了，它應該還是找得到。

**Comment by MGdesigner** [comment]
然後以前的服務整合是現在的 /src/idsrend/services/ 
我新的eclipse設定，是Javaee模式，進入點是IDSrendServlet.java

Jetty的進入點改名為 HttpserverJetty.java

**Comment by sih4sing5hong5** [comment]
修好矣
