### ISSUE TITLE
支援更多圖片類型輸出

### ISSUE THREAD

**Issue by Sea-n** [sih4sing5hong5/han3_ji7_tsoo1_kian3#23]
如 JPG WebP GIF 等，
在串接其他服務使用時將會更方便

**Comment by sih4sing5hong5** [comment]
目前[IDSrendServlet控制程式](https://github.com/sih4sing5hong5/han3_ji7_tsoo1_kian3/blob/master/src/idsrend/services/IDSrendServlet.java#L203)和[IDSrendService產生檔案](https://github.com/sih4sing5hong5/han3_ji7_tsoo1_kian3/blob/master/src/idsrend/services/IDSrendService.java#L269)

jpg當時用內建的java函式會出錯
每種圖片格式可能都要找相對應的函式庫來用

**Comment by sih4sing5hong5** [comment]
可以幫忙查有什麼好用的函式庫嗎～～
