### ISSUE TITLE
執行指令說明

### ISSUE THREAD

**Issue by sih4sing5hong5** [sih4sing5hong5/han3_ji7_tsoo1_kian3#27]
目前我這邊跑不起來，可以麻煩 @MGdesigner 列一下要按怎下指令嗎XDD

1. 執行（src）
2. 單元試驗（unittest）
3. 功能試驗（test）

**Comment by MGdesigner** [comment]
好的。23其實我還不會XD我先說你提到的執行部份：
1.Eclipse要安裝Javaee的模式（ Java EE perspective）、Tomcat要安裝設定起來（Ubuntu的話，請參考[本篇](http://www.ajopaul.com/2015/06/23/setup-tomcat7-as-server-in-eclipse-luna-under-ubuntu-linux/)），使得可以由Eclipse啟動關閉 Tomcat，而不是Tomcat自己隨著系統開機就一直開著
2.Eclipse開啟javaee開發模式，匯入這個專案
3.（列三種執行法）然後按Java EE perspective 上面有一個執行按鈕，按下去，這個專案就會被編譯、佈署進入tomcat server（是的，我之前有設定過，你就可以直接這樣用）
3.2第二種執行法：在Project Explorer裡面，對著專案名稱按出右鍵選單，找到"run as"，次選單選"run as server" ，然後一樣就會同3開始佈署、運作起來
3.3 找到 src/idsrend.services 底下的IDSrendServlet.java按右鍵選單，一樣用run as server

4執行起來以後，他會自動去開瀏覽器帶出連結，不過是空字串，請改下 http://localhost:8080/idsrender/⿴辶⿴宀⿱珤⿰隹⿰貝招.png?字體=楷體 就會動了

然後，程式改改改，改完要重新佈署到tomcat，記得先關tomcat，然後再重新run as server

另外附上非開發階段的執行法，要從eclipse裡面選單File-export，出來的視窗選web-warfile，來產生我們需要的war佈署檔。以我為例，就是把這個war scp到遠端的美國主機，然後要那邊的tomcat啟動這個程式（一個tomcat上會掛很多的網路應用程式）。

**Comment by sih4sing5hong5** [comment]
`tomcat`聽起來好像是佈署吧
這樣人工測會不方便吧？

所以原本的`Jetty`已經不能單獨執行了？

**Comment by MGdesigner** [comment]
關於tomcat佈署，其實不會慢，因為是在localhost端，而且是從eclipse去控制tomcat，此外可以發現實際佈署到server時會發生的問題，加以修正。

Jetty還是可以跑，但是會出錯，讀不到資源檔，因為資源路徑位置不同了。目前的設定，是為了符合servlet的規格，所以現在在資源檔裡面的cc.char_indexingtool下的MergedFont.java，資源檔的取得我現在改成執行時期的取得classe的工作目錄的路徑： this.getClass().getResource("/").getPath()，然後透過  工作目錄.getParent()+字體位置[i] 來取得實際的字型檔位置

這麼作，是因為Java Servlet的佈署規格，所有東西都要放在WEB-INF目錄，也就是現在的目錄規劃，font lib classes都在WEB-INF底下（lib要留意，jar不能再放子目錄，不然Java應用伺服器會找不到次目錄的jar檔）。

Jetty要正確跑的話，應該是只要把application型態編譯的結果-classes目錄指定放到WebContent-WEB-INF裡面，就可以正確執行了，不知道Eclipse可不可以指定Java applicaiton編譯出來classes的路徑跟執行時期的路徑？如果不行的話，改目前的sh檔或者用ant等自動編譯工具來設定啟動方法應該也可以解決。

**Comment by MGdesigner** [comment]
sorry，發現超簡單的解法：
Eclipse編譯Java application出來的classes，是放在build底下裡面，所以設定一個叫font的symbolic link指到WebContent-  WEB-INF底下的font目錄即可， Jetty就也可以運作了。

**Comment by sih4sing5hong5** [comment]
我直接跑`HttpserverJetty`會遇到
```
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	The type javax.servlet.Servlet cannot be resolved. It is indirectly referenced from required .class files
	The method addServletWithMapping(String, String) in the type ServletHandler is not applicable for the arguments (Class<IDSrendServlet>, String)

	at idsrend.services.HttpserverJetty.main(HttpserverJetty.java:56)

```
是缺了什麼嗎？

我用的是eclipse Neon java EE配java 7

**Comment by MGdesigner** [comment]
缺少servlet. jar 抱歉我拿掉它了，那時是因為 tomcat等javaee伺服器自己都有，想節省一點部署檔的大小，就拿掉了orz，你
checkout以前的舊版，把 servlet. jar複製到現在 web-inf 底下的lib目錄應該就可以了
2016年6月24日 下午8:56於 "薛丞宏" <notifications@github.com>寫道：
