### ISSUE TITLE
包圍部首 "⺄", "飞","𠘨"不能使用 

### ISSUE THREAD

**Issue by leo424y** [sih4sing5hong5/han3_ji7_tsoo1_kian3#30]

**Comment by leo424y** [comment]
我在猜應該因為是 "簡體字部首?" 此系統不支援?

**Comment by sih4sing5hong5** [comment]
直接像 #29 加到程式不行嗎？

我看是有這個部件的

**Comment by leo424y** [comment]
直接顯示可以，但碰到包圍型則無法([已更新字根](https://github.com/sih4sing5hong5/han3_ji7_tsoo1_kian3/commit/709ac85cb89f91ca7d462793ed27b651abcdefc2))。
https://tools.wmflabs.org/idsgen/%E2%BF%B9%E2%BA%84%E8%99%AB.png?%E5%AD%97%E9%AB%94=

**Comment by sih4sing5hong5** [comment]
想請問你都是怎麼試的？

我的做法都是先去[意傳](http://意傳.台灣/%E7%B7%9A%E4%B8%8A%E7%B5%84%E5%AD%97)試
試的時候，包圍符號直接用`⿴`就行了，程式內部會自動轉

我這邊試`⺄`、`飞`都可以
<http://漢字.意傳.台灣/%E2%BF%B4%E2%BA%84%E7%9B%AE.png?%E5%AD%97%E9%AB%94=%E5%AE%8B%E9%AB%94>
<http://漢字.意傳.台灣/%E2%BF%B4%E9%A3%9E%E7%9B%AE.png?%E5%AD%97%E9%AB%94=%E5%AE%8B%E9%AB%94>

不過`𠘨`還沒列入部首
我以前好像沒[分類](https://github.com/sih4sing5hong5/han3_ji7_tsoo1_kian3/issues/26#issuecomment-228208605)到`𠘨`這種往外勾的
這可能就要多加兩三個程式檔案了

**Comment by leo424y** [comment]
哈哈，我菜到以為repo更新 意傳 就會更新 沒有測到 XD 挖了新坑 有勞了！

薛丞宏 <notifications@github.com>於 2016年7月13日 週三，10:22寫道：

**Comment by sih4sing5hong5** [comment]
我也想處理自動更新的問題
我自己也很困擾 @@

我把`𠘨`這種往外勾的另外開一個issue好了
這樣比較清楚
