### ISSUE TITLE
`⿱𦥯子`後面的字會顯示不出來

### ISSUE THREAD

**Issue by sih4sing5hong5** [sih4sing5hong5/han3_ji7_tsoo1_kian3#48]
在 https://wikimedians-tw.hackpad.com/718-o2KLaECVGza 回報的
![u2ff1](https://cloud.githubusercontent.com/assets/5996555/16914570/4df8fcee-4d25-11e6-95e7-984989e88547.png)

**Comment by Artoria2e5** [comment]
這個可能要怪 Java String 用的是 UTF-16 單元而非 Unicode code point，遇到這種 BMP 之外的字數字數很煩。
