### ISSUE TITLE
長得一樣其實unicode不一樣的字們

### ISSUE THREAD

**Issue by leo424y** [sih4sing5hong5/han3_ji7_tsoo1_kian3#53]
想把可能會用到的字都加到包圍部件清單：

可使用
口 \u56d7

尚不在部件庫
囗 \u53e3 

口水口，好打

**Comment by leo424y** [comment]
#54 #53 的新增部件  
另感謝丞宏近其熱血指導阿翔、並且無私地將心血開放給後輩們。 阿翔近期開發造字交流平台，歡迎參觀 。 http://j.mp/字造者 大松見啦!!

**Comment by sih4sing5hong5** [comment]
這擺大松無方便去 @@

**Comment by sih4sing5hong5** [comment]
網站不錯，祝你大松順利

話說 https://sheltered-oasis-97791.herokuapp.com/groups/26
R右上角尖尖的，那其實是一個bug @@

**Comment by leo424y** [comment]
中文精神無所不在! 發現BUG! 還滿有個性的尖尖bug

**Comment by MGdesigner** [comment]
Biang麵也有遇過這個尖尖，原來真的是bug XD

**Comment by sih4sing5hong5** [comment]
那是因為stroke的參數沒調
