### ISSUE TITLE
Response Content-Type

### ISSUE THREAD

**Issue by Artoria2e5** [sih4sing5hong5/han3_ji7_tsoo1_kian3#56]
放在 `<img src=...>`  標籤內的字在 Chrome 56 上無法顯示（但是直接打開卻可以），稍微看了一下回應標頭發現沒有檔案類型（Content-Type）信息，可能是個原因。

檔案格式 | MIME
----------|-------
svg|image/svg+xml
png|image/png

（我也不知道加上有沒有用，但反正加上了科學一點。）

**Comment by MGdesigner** [comment]
我花了幾小時比對研究了在使用svg的狀態，這問題不是content-type問題（已測試過回傳content-type無效），而是Mozilla系瀏覽器呈現svg圖正常，但部份webkit系瀏覽器尚未支援用img標籤來正確顯示svg圖，目前改成[ids-testing.wmflabs.org](http://ids-testing.wmflabs.org/)的extension後端會退回改用png。

跟[這個軟體](https://github.com/bpierre/webkit-svg-fixer)描述的有關

另外發現如果改用object標籤 ，用height wigth來指定顯示大小，server傳回的svg圖檔無法縮放，而是只呈現圖片的一部分。

**Comment by Artoria2e5** [comment]
糾正一下自己，並不是「那個軟體」的事情。

用 GitHub 顯示[這裡的圖片](https://github.com/AOSC-Dev/translations)沒有問題，所以應該還是伺服器配置問題。Content-type 測試的時候加 charset 了嗎？

![測試圖](https://camo.githubusercontent.com/a5c23d60ae5a35428644cda3c4228b9eda41c0f7/68747470733a2f2f63646e2e7261776769742e636f6d2f414f53432d4465762f7472616e736c6174696f6e732f6d61737465722f776f726b666c6f772e737667)

Response Header
```
HTTP/1.1 200 OK
Cache-Control: max-age=315360000
Content-Security-Policy: default-src 'none'; img-src data:; style-src 'unsafe-inline'
Content-Type: image/svg+xml;charset=utf-8
Expires: Thu, 31 Dec 2037 23:55:55 GMT
Server: github-camo (096b6b26)
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
X-GitHub-Request-Id: 689C5A24:0867:8924F4D:582CDD07
Content-Length: 4505
Accept-Ranges: bytes
Date: Wed, 16 Nov 2016 22:28:19 GMT
Via: 1.1 varnish
Age: 123
Connection: keep-alive
X-Served-By: cache-jfk8127-JFK
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1479335299.209557,VS0,VE0
X-Fastly-Request-ID: 5fa54c3765e71df7f3b518fef9d267df522ff614
Timing-Allow-Origin: https://github.com
```

**Comment by MGdesigner** [comment]
確認，確實抓這個svg圖檔可以。

順便比對一下：
`<a href="http://漢字.意傳.台灣/%E2%BF%B4%E8%BE%B6%E2%BF%B4%E5%AE%80%E2%BF%B1%E7%8F%A4%E2%BF%B0%E9%9A%B9%E2%BF%B0%E8%B2%9D%E6%8B%9B.svg?%E5%AD%97%E9%AB%94=%E5%AE%8B%E9%AB%94" target="_blank">
  <img src="http://漢字.意傳.台灣/%E2%BF%B4%E8%BE%B6%E2%BF%B4%E5%AE%80%E2%BF%B1%E7%8F%A4%E2%BF%B0%E9%9A%B9%E2%BF%B0%E8%B2%9D%E6%8B%9B.svg?%E5%AD%97%E9%AB%94=%E5%AE%8B%E9%AB%94" alt="測試圖" style="max-width:100%;">
</a>
`
<a href="http://漢字.意傳.台灣/%E2%BF%B4%E8%BE%B6%E2%BF%B4%E5%AE%80%E2%BF%B1%E7%8F%A4%E2%BF%B0%E9%9A%B9%E2%BF%B0%E8%B2%9D%E6%8B%9B.svg?%E5%AD%97%E9%AB%94=%E5%AE%8B%E9%AB%94" target="_blank">
  <img src="http://漢字.意傳.台灣/%E2%BF%B4%E8%BE%B6%E2%BF%B4%E5%AE%80%E2%BF%B1%E7%8F%A4%E2%BF%B0%E9%9A%B9%E2%BF%B0%E8%B2%9D%E6%8B%9B.svg?%E5%AD%97%E9%AB%94=%E5%AE%8B%E9%AB%94" alt="測試圖" style="max-width:100%;">
</a>
